//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteTorrentClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RssItemCodec {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RssItemCodec() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteTorrentClient.Resources.RssItemCodec", typeof(RssItemCodec).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DivX.
        /// </summary>
        internal static string DIVX {
            get {
                return ResourceManager.GetString("DIVX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H264.
        /// </summary>
        internal static string H264 {
            get {
                return ResourceManager.GetString("H264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG.
        /// </summary>
        internal static string MPEG {
            get {
                return ResourceManager.GetString("MPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG-2.
        /// </summary>
        internal static string MPEG2 {
            get {
                return ResourceManager.GetString("MPEG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG-4.
        /// </summary>
        internal static string MPEG4 {
            get {
                return ResourceManager.GetString("MPEG4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real.
        /// </summary>
        internal static string REAL {
            get {
                return ResourceManager.GetString("REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC1.
        /// </summary>
        internal static string VC1 {
            get {
                return ResourceManager.GetString("VC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMV.
        /// </summary>
        internal static string WMV {
            get {
                return ResourceManager.GetString("WMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMV-HD.
        /// </summary>
        internal static string WMVHD {
            get {
                return ResourceManager.GetString("WMVHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X264.
        /// </summary>
        internal static string X264 {
            get {
                return ResourceManager.GetString("X264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xvid.
        /// </summary>
        internal static string XVID {
            get {
                return ResourceManager.GetString("XVID", resourceCulture);
            }
        }
    }
}
