//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteTorrentClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RssItemQuality {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RssItemQuality() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteTorrentClient.Resources.RssItemQuality", typeof(RssItemQuality).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSRip.
        /// </summary>
        internal static string DSRIP {
            get {
                return ResourceManager.GetString("DSRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVBRip.
        /// </summary>
        internal static string DVBRIP {
            get {
                return ResourceManager.GetString("DVBRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVDR.
        /// </summary>
        internal static string DVDR {
            get {
                return ResourceManager.GetString("DVDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVDRip.
        /// </summary>
        internal static string DVDRIP {
            get {
                return ResourceManager.GetString("DVDRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVDScr.
        /// </summary>
        internal static string DVDSCR {
            get {
                return ResourceManager.GetString("DVDSCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1080i.
        /// </summary>
        internal static string HD1080I {
            get {
                return ResourceManager.GetString("HD1080I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1080p.
        /// </summary>
        internal static string HD1080P {
            get {
                return ResourceManager.GetString("HD1080P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 720p.
        /// </summary>
        internal static string HD720P {
            get {
                return ResourceManager.GetString("HD720P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDTV.
        /// </summary>
        internal static string HDTV {
            get {
                return ResourceManager.GetString("HDTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.HDTV.
        /// </summary>
        internal static string HRHDTV {
            get {
                return ResourceManager.GetString("HRHDTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.PDTV.
        /// </summary>
        internal static string HRPDTV {
            get {
                return ResourceManager.GetString("HRPDTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDTV.
        /// </summary>
        internal static string PDTV {
            get {
                return ResourceManager.GetString("PDTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SatRip.
        /// </summary>
        internal static string SATRIP {
            get {
                return ResourceManager.GetString("SATRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVCD.
        /// </summary>
        internal static string SVCD {
            get {
                return ResourceManager.GetString("SVCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVRip.
        /// </summary>
        internal static string TVRIP {
            get {
                return ResourceManager.GetString("TVRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebRip.
        /// </summary>
        internal static string WEBRIP {
            get {
                return ResourceManager.GetString("WEBRIP", resourceCulture);
            }
        }
    }
}
